---
- name: Create systemd directories
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
- name: Define containerd cgroup
  copy:
    dest: /etc/systemd/system/docker.service.d/00-cgroup-systemd.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: "Update APT cache"
  apt:
    update_cache: yes
- name: "Install docker requirements"
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: "Add docker repository key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
- name: "Add docker repository"
  apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
- name: "Install docker"
  apt:
    name:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"
    update_cache: yes
