---
- name: Create systemd directories
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
- name: Set kubelet args
  copy:
    dest: /etc/systemd/system/kubelet.service.d/20-hcloud.conf
    content: |
      [Service]
      Environment="KUBELET_EXTRA_ARGS=--cloud-provider=external"
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: "Update APT cache"
  apt:
    update_cache: yes
- name: "Install kubernetes requirements"
  apt:
    name:
    - apt-transport-https
- name: "Add kubernetes repository key"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: "Add kubernetes repository"
  apt_repository:
    filename: kubernetes
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
- name: "Install kubelet, kubeadm, kubectl"
  apt:
    name:
    - "kubelet={{ k8s_version }}-00"
    - "kubeadm={{ k8s_version }}-00"
    - "kubectl={{ k8s_version }}-00"
    update_cache: yes
- name: "Fix versions of kubelet, kubeadm & kubectl"
  dpkg_selections:
    name: "{{item}}"
    selection: hold
  with_items:
  - kubelet
  - kubeadm
  - kubectl
- name: "Enable network traffic between pods"
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      # Allow IP forwarding for kubernetes
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.ipv6.conf.default.forwarding = 1
- name: "Reload kernel configuration to apply network traffic configuration"
  command: sysctl -p
